DPDK_VER = 22.11.1

DPDK_DIR := $(CD)/deps/dpdk
DPDK_SRC_DIR := $(DPDK_DIR)/dpdk-$(DPDK_VER)
DPDK_INSTALL_DIR := $(DPDK_DIR)/install
DPDK_PKG_CONFIG_PATH := $(DPDK_INSTALL_DIR)/lib/x86_64-linux-gnu/pkgconfig
DPDK_PKG_CONFIG_FILE := $(DPDK_PKG_CONFIG_PATH)/libdpdk.pc
CFLAGS += $(shell PKG_CONFIG_PATH=$(DPDK_PKG_CONFIG_PATH) $(PKGCONF) --cflags libdpdk)
LDFLAGS += $(shell PKG_CONFIG_PATH=$(DPDK_PKG_CONFIG_PATH) $(PKGCONF) --libs libdpdk)

CFLAGS += -DALLOW_EXPERIMENTAL_API
CFLAGS += -DALLOW_INTERNAL_API

CFLAGS += -I$(DPDK_SRC_DIR)/lib/ethdev
CFLAGS += -I$(DPDK_SRC_DIR)/lib/eal/include
CFLAGS += -I$(DPDK_SRC_DIR)/drivers/bus/vdev
